### ISSUE TITLE
DSMR-Fluvius-S1-port-receiver

### ISSUE THREAD

**Issue by MaxVandenbussche** [tribp/DSMR-Fluvius-S1-port-simulator#1]
It seems the README.md is mentioning and linking to the receiver repo.
This repository does not exist anymore. What happened to the receiver project?

BR,
Max

**Comment by tribp** [comment]
Max, it still has a "todo" next to it. Due to a lack of time and public intrest I didn't yet cleaned up my code to make it publicly available :-(
Greetings Peter
