### ISSUE TITLE
Receiver code

### ISSUE THREAD

**Issue by DarkShadowNight** [tribp/DSMR-Fluvius-S1-port-simulator#3]
Hello,

I guess you are familiar with new solar panels regulations in Belgium.
Long way short, I receive no compensation at all for injected power like many others.
So why should I accept this?

So I want to start a project, where zero injection is the goal and hope I can help other enthousiasts.
For example, control an electric heater with a triac during winter / mid season to avoid injection, controlling water pump, ...

Can you share your raw receiver code?
The P1 port is too slow to interact on sudden changes.

I know it's not the right thing to do for the environment, but the system motivates to waste energy when it's available this way.
I'm hoping to get some media attention when finished.

I could write the code myself but guessing to process the signal to a realtime power (one period floating?) would be difficult.

Thanks

**Comment by MaxVandenbussche** [comment]
Hello. I live in Belgium and this is exactly what I do.
I publish data from the P1 port on a MQTT broker and I use this data to turn on/off electric heaters or other equipment in the house. This way I can achieve _almost_ net-zero. I you want we can get in touch and I can share some code and hardware.

But indeed the P1 port only has data every single second, but this means, worst case, that only a second (+network delay) of that power is drawn from the net. But the energy in that single second is quite small, so for now this is acceptable for me.
A system that would take S1 data and do real time load modulation would be much more difficult (but not impossible) and is currently out of scope for me at the moment.

Also keep in mind that a triac with a phase-cut power modulation strategy will not work to get a near perfect net-zero consumption using the S1 data. You would need some sort of active PFC circuit to achieve this properly.

**Comment by DarkShadowNight** [comment]
Hello Max,

I also have P1 information available on MQTT so maybe I should try that and accept 1 second error.
It would be a piece of cake to subscribe a topic and turn on and off a load with SSR or control the air conditioning by replicating Daikin IR transmitter commands.
(or sent the actual power with NRF24 modules to some simple Arduinos around the house,)

I only have 1,5 kW solar inverter (what is more than enough for our own consumption year based, well not anymore now).
Based on switching on an off a load of for example 1 kW or so would be quite limited in useable time.

I don't think it should be that difficult to do a floating calculation of the power for let's say one period (20 ms) if an ESP has enough capabilities plus it's non-realtime behaviour.

I'm not sure if a triac will cause issues, I'm guessing the DSMR will also average it's readings (second based?).
The key is to be faster ;-)
